### ISSUE TITLE
Tearing-free patch

### ISSUE THREAD

**Issue by KosmiK2001** [ethus3h/compiz-reloaded-overlay#12]
Good afternoon. 
I have been using the compiz patch for a very long time. This patch was originally intended to be a "great victory" over tearing. But now this patch makes compiz work (IMO!) extremely smooth.
And it doesn't matter if it's "intel" or "nvidia" or "nouveau".
(right now - 8800GT under nouveau.)
(x11-wm/compiz)
Thx!!!
[nvidia_teearing.patch](https://drive.google.com/file/d/1gpaIiijDBWXG4XpVfeO-mv4By4wOnBJa/view?usp=sharing)

**Comment by ethus3h** [comment]
Thanks for the patch! This repository only has packaging information for Compiz, though — since this is a patch for Compiz itself, it should get sent to: https://gitlab.com/compiz/compiz-core

P.S. When you send it in, I suggest attaching it directly to the issue report, or adding it as a merge request, since people tend to not be fond of Google :)

Good luck!
