### ISSUE TITLE
x11-plugins/compiz-plugins-main-0.8.16 - no configure script

### ISSUE THREAD

**Issue by r7l** [ethus3h/compiz-reloaded-overlay#3]
When trying to update compiz, it breaks with this error:

`ERROR: x11-plugins/compiz-plugins-main-0.8.16::compiz-reloaded failed (configure phase):
  no configure script found`

`Call stack:
         ebuild.sh, line  124:  Called src_configure
       environment, line 2264:  Called econf '--enable-fast-install' '--disable-static'
  phase-helpers.sh, line  724:  Called die
The specific snippet of code:
  		die "no configure script found"`

I have not tried to update the other packages. Any way to fix this?

**Comment by ethus3h** [comment]
Hi! Sorry I didn't get back to you on this sooner, I've been swamped with homework. I'll look at this and try to fix it. Sorry for the trouble. Thank you for the report!

**Comment by ethus3h** [comment]
This should be fixed now! Sorry it was broken for so long. Would you mind updating the overlay and trying the build again? Thanks!

(For the record, the problem was that I hadn't updated some ebuilds to run `eautoreconf` to account for the packages no longer coming with a pre-generated configure script.)

**Comment by r7l** [comment]
Haven't had time to try earlier but i just did. It works perfectly! Thanks allot for the fix!

**Comment by ethus3h** [comment]
No problem! Thanks for bringing it to my attention!
